version: "3.8"
services:
  gcc:
    build:
      context: .
      dockerfile: containers/gcc/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src
    ports:
      - "2222:22"
    tty: true
    cap_add:
      - SYS_PTRACE